jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Start Firebase Server
        run: firebase serve &


      - name: Wait for Server
        run: npx wait-on http://localhost:5000
        # Ensures the server is up and accessible before running tests

      - name: Run Cypress Tests
        run: npx cypress run